[helpers]

[default]
depends = []

[default.files]
"hypr" = "~/.config/hypr"
"waybar" = "~/.config/waybar"
"walker" = "~/.config/walker"
".zshrc" = "~/.zshrc"
".condarc" = "~/.condarc"

[default.variables]

[settings]
default_target_type = "automatic"
